name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    run: |-
      echo '
        target: ${{ env.dist }}
        setup:
          run: pnpm build
          cwd: ./ember-toucan-styles
        expect: |
          _app_/services/theme-manager.js
          index.js
          index.js.map
          index.d.ts
          index.d.ts.map
          scrollbar.css
          services/theme-manager.js
          services/theme-manager.js.map
          services/theme-manager.d.ts
          test-support/index.js
          test-support/index.d.ts
          test-support/index.js.map
      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
